import Head from 'next/head'
import { GetServerSideProps } from 'next/types'
// eslint-disable-next-line camelcase
import { unstable_getServerSession } from 'next-auth/next'
import { buildNextAuthOptions } from './api/auth/[...nextauth]'
import { Header } from '@/components/Header'
import { SummaryTable } from '@/components/SummaryTable'

export default function Home() {
  return (
    <>
      <Head>
        <title>Habits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen md:h-screen py-10 md:py-0 flex items-center justify-center">
        <div className="w-full max-w-5xl px-6 flex flex-col gap-16">
          <Header />
          <SummaryTable />
        </div>
      </div>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const session = await unstable_getServerSession(
    req,
    res,
    buildNextAuthOptions(req, res),
  )

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  return {
    props: {
      session,
    },
  }
}
