// eslint-disable-next-line camelcase
import { unstable_getServerSession } from 'next-auth/next'
import Head from 'next/head'
import { GetServerSideProps } from 'next/types'
import { buildNextAuthOptions } from './api/auth/[...nextauth]'

export default function Home() {
  return (
    <>
      <Head>
        <title>Habits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello word</h1>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const session = await unstable_getServerSession(
    req,
    res,
    buildNextAuthOptions(req, res),
  )

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  return {
    props: {
      session,
    },
  }
}
