import { Button } from '@/components/Button'
import Head from 'next/head'
import { GoogleLogo } from 'phosphor-react'
import { signIn } from 'next-auth/react'
import { authOptions } from './api/auth/[...nextauth]'
import { GetServerSideProps } from 'next'
// eslint-disable-next-line camelcase
import { unstable_getServerSession } from 'next-auth/next'

export default function Login() {
  async function handleSignIn() {
    await signIn('google')
  }

  return (
    <>
      <Head>
        <title>Habits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center h-screen">
        <img src="./logo.svg" alt="logo do site" />
        <h1 className="text-2xl mt-3">
          Leve sua produtividade para um próximo nível
        </h1>
        <div className="bg-zinc-900 rounded-2xl p-10 flex flex-col gap-6 items-center justify-center mt-20 min-w-[340px]">
          <h2 className="text-4xl font-bold">Entrar</h2>
          <Button variant="google" size="sm" fullWidth onClick={handleSignIn}>
            <GoogleLogo weight="fill" />
            Google
          </Button>
        </div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await unstable_getServerSession(ctx.req, ctx.res, authOptions)

  if (session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: {},
  }
}
